#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""BNF to CNF converter and DPLL solver
by Ziyang Zeng (zz2960)
Spring 2022
"""

import argparse
from solving import DPLL, text_to_cnf_rep


def main():
    cnf_rep = text_to_cnf_rep("""
P Q !R
P !Q R
!P Q
!Q R W
!R W
!W !X
!W X
    """)
    solver = DPLL(cnf_rep, verbose=True)
    result = solver.solve()
    if result:
        result = solver.fill_unbounded_atoms()
    print(result)


if __name__ == '__main__':
    main()
